using System;
using System.Collections.Generic;
using System.Text;

namespace MartinCl2.OpenCl
{
    public enum DeviceInfo : uint
    {
        DEVICE_TYPE                                   = 0x1000,
        DEVICE_VENDOR_ID                              = 0x1001,
        DEVICE_MAX_COMPUTE_UNITS                      = 0x1002,
        DEVICE_MAX_WORK_ITEM_DIMENSIONS               = 0x1003,
        DEVICE_MAX_WORK_GROUP_SIZE                    = 0x1004,
        DEVICE_MAX_WORK_ITEM_SIZES                    = 0x1005,
        DEVICE_PREFERRED_VECTOR_WIDTH_CHAR            = 0x1006,
        DEVICE_PREFERRED_VECTOR_WIDTH_SHORT           = 0x1007,
        DEVICE_PREFERRED_VECTOR_WIDTH_INT             = 0x1008,
        DEVICE_PREFERRED_VECTOR_WIDTH_LONG            = 0x1009,
        DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT           = 0x100A,
        DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE          = 0x100B,
        DEVICE_MAX_CLOCK_FREQUENCY                    = 0x100C,
        DEVICE_ADDRESS_BITS                           = 0x100D,
        DEVICE_MAX_READ_IMAGE_ARGS                    = 0x100E,
        DEVICE_MAX_WRITE_IMAGE_ARGS                   = 0x100F,
        DEVICE_MAX_MEM_ALLOC_SIZE                     = 0x1010,
        DEVICE_IMAGE2D_MAX_WIDTH                      = 0x1011,
        DEVICE_IMAGE2D_MAX_HEIGHT                     = 0x1012,
        DEVICE_IMAGE3D_MAX_WIDTH                      = 0x1013,
        DEVICE_IMAGE3D_MAX_HEIGHT                     = 0x1014,
        DEVICE_IMAGE3D_MAX_DEPTH                      = 0x1015,
        DEVICE_IMAGE_SUPPORT                          = 0x1016,
        DEVICE_MAX_PARAMETER_SIZE                     = 0x1017,
        DEVICE_MAX_SAMPLERS                           = 0x1018,
        DEVICE_MEM_BASE_ADDR_ALIGN                    = 0x1019,
        DEVICE_MIN_DATA_TYPE_ALIGN_SIZE               = 0x101A,
        DEVICE_SINGLE_FP_CONFIG                       = 0x101B,
        DEVICE_GLOBAL_MEM_CACHE_TYPE                  = 0x101C,
        DEVICE_GLOBAL_MEM_CACHELINE_SIZE              = 0x101D,
        DEVICE_GLOBAL_MEM_CACHE_SIZE                  = 0x101E,
        DEVICE_GLOBAL_MEM_SIZE                        = 0x101F,
        DEVICE_MAX_CONSTANT_BUFFER_SIZE               = 0x1020,
        DEVICE_MAX_CONSTANT_ARGS                      = 0x1021,
        DEVICE_LOCAL_MEM_TYPE                         = 0x1022,
        DEVICE_LOCAL_MEM_SIZE                         = 0x1023,
        DEVICE_ERROR_CORRECTION_SUPPORT               = 0x1024,
        DEVICE_PROFILING_TIMER_RESOLUTION             = 0x1025,
        DEVICE_ENDIAN_LITTLE                          = 0x1026,
        DEVICE_AVAILABLE                              = 0x1027,
        DEVICE_COMPILER_AVAILABLE                     = 0x1028,
        DEVICE_EXECUTION_CAPABILITIES                 = 0x1029,
        DEVICE_QUEUE_PROPERTIES                       = 0x102A,    /* deprecated */
        DEVICE_QUEUE_ON_HOST_PROPERTIES               = 0x102A,
        DEVICE_NAME                                   = 0x102B,
        DEVICE_VENDOR                                 = 0x102C,
        DRIVER_VERSION                                = 0x102D,
        DEVICE_PROFILE                                = 0x102E,
        DEVICE_VERSION                                = 0x102F,
        DEVICE_EXTENSIONS                             = 0x1030,
        DEVICE_PLATFORM                               = 0x1031,
        DEVICE_DOUBLE_FP_CONFIG                       = 0x1032,
        /* 0x1033 reserved for CL_DEVICE_HALF_FP_CONFIG */
        DEVICE_PREFERRED_VECTOR_WIDTH_HALF            = 0x1034,
        DEVICE_HOST_UNIFIED_MEMORY                    = 0x1035,   /* deprecated */
        DEVICE_NATIVE_VECTOR_WIDTH_CHAR               = 0x1036,
        DEVICE_NATIVE_VECTOR_WIDTH_SHORT              = 0x1037,
        DEVICE_NATIVE_VECTOR_WIDTH_INT                = 0x1038,
        DEVICE_NATIVE_VECTOR_WIDTH_LONG               = 0x1039,
        DEVICE_NATIVE_VECTOR_WIDTH_FLOAT              = 0x103A,
        DEVICE_NATIVE_VECTOR_WIDTH_DOUBLE             = 0x103B,
        DEVICE_NATIVE_VECTOR_WIDTH_HALF               = 0x103C,
        DEVICE_OPENCL_C_VERSION                       = 0x103D,
        DEVICE_LINKER_AVAILABLE                       = 0x103E,
        DEVICE_BUILT_IN_KERNELS                       = 0x103F,
        DEVICE_IMAGE_MAX_BUFFER_SIZE                  = 0x1040,
        DEVICE_IMAGE_MAX_ARRAY_SIZE                   = 0x1041,
        DEVICE_PARENT_DEVICE                          = 0x1042,
        DEVICE_PARTITION_MAX_SUB_DEVICES              = 0x1043,
        DEVICE_PARTITION_PROPERTIES                   = 0x1044,
        DEVICE_PARTITION_AFFINITY_DOMAIN              = 0x1045,
        DEVICE_PARTITION_TYPE                         = 0x1046,
        DEVICE_REFERENCE_COUNT                        = 0x1047,
        DEVICE_PREFERRED_INTEROP_USER_SYNC            = 0x1048,
        DEVICE_PRINTF_BUFFER_SIZE                     = 0x1049,
        DEVICE_IMAGE_PITCH_ALIGNMENT                  = 0x104A,
        DEVICE_IMAGE_BASE_ADDRESS_ALIGNMENT           = 0x104B,
        DEVICE_MAX_READ_WRITE_IMAGE_ARGS              = 0x104C,
        DEVICE_MAX_GLOBAL_VARIABLE_SIZE               = 0x104D,
        DEVICE_QUEUE_ON_DEVICE_PROPERTIES             = 0x104E,
        DEVICE_QUEUE_ON_DEVICE_PREFERRED_SIZE         = 0x104F,
        DEVICE_QUEUE_ON_DEVICE_MAX_SIZE               = 0x1050,
        DEVICE_MAX_ON_DEVICE_QUEUES                   = 0x1051,
        DEVICE_MAX_ON_DEVICE_EVENTS                   = 0x1052,
        DEVICE_SVM_CAPABILITIES                       = 0x1053,
        DEVICE_GLOBAL_VARIABLE_PREFERRED_TOTAL_SIZE   = 0x1054,
        DEVICE_MAX_PIPE_ARGS                          = 0x1055,
        DEVICE_PIPE_MAX_ACTIVE_RESERVATIONS           = 0x1056,
        DEVICE_PIPE_MAX_PACKET_SIZE                   = 0x1057,
        DEVICE_PREFERRED_PLATFORM_ATOMIC_ALIGNMENT    = 0x1058,
        DEVICE_PREFERRED_GLOBAL_ATOMIC_ALIGNMENT      = 0x1059,
        DEVICE_PREFERRED_LOCAL_ATOMIC_ALIGNMENT       = 0x105A,
        DEVICE_IL_VERSION                             = 0x105B,
        DEVICE_MAX_NUM_SUB_GROUPS                     = 0x105C,
        DEVICE_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS = 0x105D
    }
}
